name: Project Build

on:
  push:
    branches: [ master, bconn98-patch-1 ]
  pull_request:
    branches: [ master, bconn98-patch-1 ]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

#    - name: Set up Go 1.x
#      uses: actions/setup-go@v2
#      with:
#        go-version: ^1.15.5

#    - name: Check out code into the Go module directory
#      uses: actions/checkout@v2

    - name: Build
      run: go build -v .

  test:
    name: Test
    runs-on: windows-latest
    steps:

#      - name: Set up Go 1.x
#          uses: actions/setup-go@v2
#          with:
#            go-version: ^1.15.5

#      - name: Check out code into the Go module directory
#          uses: actions/checkout@v2

#      - name: Get dependencies
#          run: |
#            go version
#            go get -v ./...

      - name: Build
          run: go build -v .

      - name: Test
          run: cd utils; go test -v .

  deploy:
    name: Deploy
    runs-on: windows-latest
    steps:

#      - name: Set up Go 1.x
#          uses: actions/setup-go@v2
#          with:
#            go-version: ^1.15.5

#      - name: Check out code into the Go module directory
#          uses: actions/checkout@v2

      - name: Deploy
          run: